spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/afterreading
    username: root
    password: 1529
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.wonyoung.afterreading